# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

agrant.require_version ">=1.9.3"

HOST_IP = "192.168.33.10"

$install_go = <<SCRIPT
yum install -y vim gcc
curl -o go1.8.3.linux-amd64.tar.gz https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.8.3.linux-amd64.tar.gz && rm -rf go1.8.3.linux-amd64.tar.gz
mkdir -p $HOME/golang1.8.3
echo "export GOROOT=$HOME/golang1.8.3" >> /etc/profile
echo "export PATH=$PATH:/usr/local/go/bin" >> /etc/profile
mv /vagrant/.vim ~/ && mv /vagrant/.vim /home/vagrant/
mv /vagrant/.vimrc ~/ && mv /vagrant/.vimrc /home/vagrant
mv /vagrant/.vimrc.bundles ~/ && mv /vagrant/.vimrc.bundles /home/vagrant
SCRIPT

$install_ctag = <<SCRIPT
curl -o ctags.tar.gz https://jaist.dl.sourceforge.net/project/ctags/ctags/5.8/ctags-5.8.tar.gz
tar -xzf ctags.tar.gz && cd ctags-5.8
./configure --prefix=/usr && make && make install
rm -rf ctags*
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.define "go" do |centos7|
    centos7.vm.box = "centos/7"
    centos7.vm.network "private_network", ip: HOST_IP
    centos7.vm.hostname = "go"
    centos7.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    centos7.vm.provision "shell", inline: $install_go
    centos7.vm.provision "shell", inline: $install_ctag
  end
  config.vm.box_check_update = false
end
